name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test:ci

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build and export Next.js app
        run: npm run build
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL }}
          vercel-org-id: esteam
          vercel-project-id: neuralclocks-challenge